### PR TITLE
Fixed Nexus 10 (manta) scripts

### PR DESCRIPTION
**Pull request by lnxsr**

### CODE REVIEW

**Comment by MariusQuabeck** [comment]
Thank you for taking the time to fix this but I have to change many things from your pull request. manta will bootloop without gapps (thats why that option is intentionally not available), its "Lineage OS" and a short description of what you've changed would be useful next time ;)

This will take some time to merge but I'll look into it.
Thanks
Marius

**Comment by lnxsr** [comment]
Thank you for quick response.
I installed without gapps multiple times during test and never got a boot loop.
Well, I first used "Lineage OS" but then noticed that in other devices LineageOS was used, so I decided to normalize.

Sorry for the missing description. Just for the record:
Nexus 10 (manta) script fixes
- Fixed factory Installation
- Update of Lineage OS snapshot to latest
- Migrated Cyanowogapps to Lineage OS and added it to menu

**Comment by MariusQuabeck** [comment]
oh okay. I've tried it a few weeks ago and it was still bootlooping.  "Lineage OS" should be used everywhere
I will look into this
Thanks

**Comment by MariusQuabeck** [comment]
not mergable anymore, most fixes are already in place.

**Pull request closed without merging**
